// Built-in ROS message types

// Auto-generated by ros-msg-parser

/**
 * Set the robot's name
 */
export interface SetNameRequest {
	name?: string;
}

export interface SetNameResponse {
	success?: boolean;
	message?: string;
}

export enum RobotStateMode {
	/**
	 * Idle
	 */
	MODE_IDLE = 0,
	/**
	 * Active
	 */
	MODE_ACTIVE = 1,
	/**
	 * Error
	 */
	MODE_ERROR = 2,
}

/**
 * Robot state with header, name, enum mode and pose
 */
export interface RobotState {
	/**
	 * Standard header
	 */
	header: StdMsgsHeader;
	/**
	 * Robot name
	 */
	name: string;
	mode: RobotStateMode;
	/**
	 * Current pose in map frame
	 */
	pose: GeometryMsgsPose;
}

/**
 * Composite message referencing another custom message in the same module
 */
export interface Composite {
	/**
	 * Current state
	 */
	state: RobotState;
	/**
	 * History of states
	 */
	history: RobotState[];
}

/**
 * Navigate to a target pose
 * Goal
 */
export interface NavigateGoal {
	/**
	 * Goal
	 */
	target?: GeometryMsgsPose;
}

/**
 * Feedback
 */
export interface NavigateFeedback {
	/**
	 * Feedback
	 * 0.0~1.0
	 */
	progress?: number;
}

/**
 * Result
 */
export interface NavigateResult {
	/**
	 * Result
	 */
	reached?: boolean;
}

/**
 * Standard metadata for higher-level stamped data types.
 */
export interface StdMsgsHeader {
	/**
	 * Time stamp for the data.
	 */
	stamp: BuiltinInterfacesTime;
	/**
	 * Frame this data is associated with.
	 */
	frame_id: string;
}

/**
 * Position and orientation in 3D space.
 */
export interface GeometryMsgsPose {
	/**
	 * Position in 3D space.
	 */
	position: GeometryMsgsPoint;
	/**
	 * Orientation as quaternion.
	 */
	orientation: GeometryMsgsQuaternion;
}

/**
 * Time representation.
 */
export interface BuiltinInterfacesTime {
	/**
	 * Seconds since epoch.
	 */
	sec: number;
	/**
	 * Nanoseconds since the last second.
	 */
	nanosec: number;
}

/**
 * Point representation in 3D space.
 */
export interface GeometryMsgsPoint {
	/**
	 * X coordinate.
	 */
	x: number;
	/**
	 * Y coordinate.
	 */
	y: number;
	/**
	 * Z coordinate.
	 */
	z: number;
}

/**
 * Quaternion representation for rotation.
 */
export interface GeometryMsgsQuaternion {
	/**
	 * X component.
	 */
	x: number;
	/**
	 * Y component.
	 */
	y: number;
	/**
	 * Z component.
	 */
	z: number;
	/**
	 * W component.
	 */
	w: number;
}

// End of auto-generated content
